//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc circle.hlsl /T gs_5_0 /E GS /Fo circle_gs.cso /Fc circle_gs.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12 [unused]
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPass                            cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// COLOR                    0   xyzw        1     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// m0:SV_POSITION           0   xyzw        0      POS  float   xyzw
// m0:POSITION              0   xyz         1     NONE  float   xyz 
// m0:COLOR                 0   xyzw        2     NONE  float   xyzw
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb1[20], immediateIndexed
dcl_input v[2][0].xyz
dcl_input v[2][1].xyzw
dcl_temps 3
dcl_inputprimitive line 
dcl_stream m0
dcl_outputtopology linestrip 
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyzw
dcl_maxout 2
add r0.xyz, v[1][0].xyzx, v[0][0].xyzx
mul r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
mov r0.w, l(0.500000)
dp4 r1.x, r0.xyzw, cb1[16].xyzw
mov o0.x, r1.x
dp4 r1.x, r0.xyzw, cb1[17].xyzw
mov o0.y, r1.x
dp4 r1.x, r0.xyzw, cb1[18].xyzw
mov o0.z, r1.x
dp4 r1.x, r0.xyzw, cb1[19].xyzw
add r2.xyzw, r0.xyzw, l(0.000000, 2.000000, 0.000000, 1.000000)
mov o0.w, r1.x
mov o1.xyz, r0.xyzx
mov o2.xyzw, v[0][1].xyzw
emit_stream m0
dp4 r0.x, r2.xyzw, cb1[16].xyzw
mov o0.x, r0.x
dp4 r0.x, r2.xyzw, cb1[17].xyzw
mov o0.y, r0.x
dp4 r0.x, r2.xyzw, cb1[18].xyzw
mov o0.z, r0.x
dp4 r0.x, r2.xyzw, cb1[19].xyzw
mov o0.w, r0.x
mov o1.xyz, r2.xyzx
mov o2.xyzw, v[1][1].xyzw
emit_stream m0
ret 
// Approximately 27 instruction slots used
