//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc circle.hlsl /Od /Zi /T gs_5_0 /E GS /Fo circle_gs.cso /Fc
//    circle_gs.asm
//
//
// Buffer Definitions: 
//
// cbuffer cbPass
// {
//
//   float4x4 gView;                    // Offset:    0 Size:    64 [unused]
//   float4x4 gInvView;                 // Offset:   64 Size:    64 [unused]
//   float4x4 gProj;                    // Offset:  128 Size:    64 [unused]
//   float4x4 gInvProj;                 // Offset:  192 Size:    64 [unused]
//   float4x4 gViewProj;                // Offset:  256 Size:    64
//   float4x4 gInvViewProj;             // Offset:  320 Size:    64 [unused]
//   float3 gEyePosW;                   // Offset:  384 Size:    12
//   float cbPerObjectPad1;             // Offset:  396 Size:     4 [unused]
//   float2 gRenderTargetSize;          // Offset:  400 Size:     8 [unused]
//   float2 gInvRenderTargetSize;       // Offset:  408 Size:     8 [unused]
//   float gNearZ;                      // Offset:  416 Size:     4 [unused]
//   float gFarZ;                       // Offset:  420 Size:     4 [unused]
//   float gTotalTime;                  // Offset:  424 Size:     4 [unused]
//   float gDeltaTime;                  // Offset:  428 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPass                            cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyz         0     NONE  float   xyz 
// COLOR                    0   xyzw        1     NONE  float   xyzw
// NORMAL                   0   xyz         2     NONE  float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// m0:SV_POSITION           0   xyzw        0      POS  float   xyzw
// m0:POSITION              0   xyz         1     NONE  float   xyz 
// m0:COLOR                 0   xyzw        2     NONE  float   xyzw
// m0:NORMAL                0   xyz         3     NONE  float   xyz 
//
gs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb1[25], immediateIndexed
dcl_input v[3][0].xyz
dcl_input v[3][1].xyzw
dcl_input v[3][2].xyz
dcl_temps 54
dcl_indexableTemp x0[45], 4
dcl_indexableTemp x1[9], 4
dcl_indexableTemp x2[27], 4
dcl_indexableTemp x3[60], 4
dcl_indexableTemp x4[18], 4
dcl_indexableTemp x5[9], 4
dcl_indexableTemp x6[12], 4
dcl_inputprimitive triangle 
dcl_stream m0
dcl_outputtopology trianglestrip 
dcl_output_siv o0.xyzw, position
dcl_output o1.xyz
dcl_output o2.xyzw
dcl_output o3.xyz
dcl_maxout 24

#line 211 "C:\Users\lemon\DirectX12Study\Directx12_study\12\연습문제 2\Shapes\Shaders\circle.hlsl"
dp3 r0.x, cb1[24].xyzx, cb1[24].xyzx
sqrt r0.x, r0.x
lt r0.y, r0.x, l(15.000000)
if_nz r0.y
  nop 

#line 91
  add r0.yzw, v[1][0].xxyz, v[0][0].xxyz
  mul r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000)
  add r1.xyz, v[2][0].xyzx, v[1][0].xyzx
  mul r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r2.xyz, v[0][0].xyzx, v[2][0].xyzx
  mul r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)

#line 96
  add r3.xyz, r0.yzwy, v[0][0].xyzx
  mul r3.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r4.xyz, r0.yzwy, r2.xyzx
  mul r4.xyz, r4.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r5.xyz, r2.xyzx, v[0][0].xyzx
  mul r5.xyz, r5.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r6.xyz, r0.yzwy, v[1][0].xyzx
  mul r6.xyz, r6.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r7.xyz, r1.xyzx, v[1][0].xyzx
  mul r7.xyz, r7.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r8.xyz, r0.yzwy, r1.xyzx
  mul r8.xyz, r8.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r9.xyz, r1.xyzx, r2.xyzx
  mul r9.xyz, r9.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r10.xyz, r1.xyzx, v[2][0].xyzx
  mul r10.xyz, r10.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  add r11.xyz, r2.xyzx, v[2][0].xyzx
  mul r11.xyz, r11.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
  mov x0[0].xyz, v[0][0].xyzx  // outVerts<0,1,2>
  mov x0[1].xyzw, v[0][1].xyzw  // outVerts<3,4,5,6>

#line 107
  mov r12.xyzw, x2[1].xyzw  // k<3:Inf,4:Inf,5:Inf,6:Inf>
  mov x0[3].xyz, r3.xyzx  // outVerts<10,11,12>
  mov x0[4].xyzw, r12.xyzw  // outVerts<13,14,15,16>
  mov r3.xyzw, x2[7].xyzw  // k<23:Inf,24:Inf,25:Inf,26:Inf>
  mov x0[6].xyz, r5.xyzx  // outVerts<20,21,22>
  mov x0[7].xyzw, r3.xyzw  // outVerts<23,24,25,26>
  mov r3.xyzw, x2[4].xyzw  // k<13:Inf,14:Inf,15:Inf,16:Inf>
  mov x0[9].xyz, r4.xyzx  // outVerts<30,31,32>
  mov x0[10].xyzw, r3.xyzw  // outVerts<33,34,35,36>
  mov r3.xyzw, x1[7].xyzw  // m<23:Inf,24:Inf,25:Inf,26:Inf>
  mov x0[12].xyz, r2.xyzx  // outVerts<40,41,42>
  mov x0[13].xyzw, r3.xyzw  // outVerts<43,44,45,46>
  mov r2.xyzw, x2[19].xyzw  // k<63:Inf,64:Inf,65:Inf,66:Inf>
  mov x0[15].xyz, r9.xyzx  // outVerts<50,51,52>
  mov x0[16].xyzw, r2.xyzw  // outVerts<53,54,55,56>
  mov r2.xyzw, x2[25].xyzw  // k<83:Inf,84:Inf,85:Inf,86:Inf>
  mov x0[18].xyz, r11.xyzx  // outVerts<60,61,62>
  mov x0[19].xyzw, r2.xyzw  // outVerts<63,64,65,66>
  mov r2.xyzw, x2[22].xyzw  // k<73:Inf,74:Inf,75:Inf,76:Inf>
  mov x0[21].xyz, r10.xyzx  // outVerts<70,71,72>
  mov x0[22].xyzw, r2.xyzw  // outVerts<73,74,75,76>
  mov x0[24].xyz, v[2][0].xyzx  // outVerts<80,81,82>
  mov x0[25].xyzw, v[2][1].xyzw  // outVerts<83,84,85,86>
  mov r2.xyzw, x1[1].xyzw  // m<3:Inf,4:Inf,5:Inf,6:Inf>
  mov x0[27].xyz, r0.yzwy  // outVerts<90,91,92>
  mov x0[28].xyzw, r2.xyzw  // outVerts<93,94,95,96>
  mov r2.xyzw, x2[10].xyzw  // k<33:Inf,34:Inf,35:Inf,36:Inf>
  mov x0[30].xyz, r6.xyzx  // outVerts<100,101,102>
  mov x0[31].xyzw, r2.xyzw  // outVerts<103,104,105,106>
  mov r2.xyzw, x2[16].xyzw  // k<53:Inf,54:Inf,55:Inf,56:Inf>
  mov x0[33].xyz, r8.xyzx  // outVerts<110,111,112>
  mov x0[34].xyzw, r2.xyzw  // outVerts<113,114,115,116>

#line 118
  mov r2.xyzw, x2[13].xyzw  // k<43:Inf,44:Inf,45:Inf,46:Inf>
  mov x0[36].xyz, r7.xyzx  // outVerts<120,121,122>
  mov x0[37].xyzw, r2.xyzw  // outVerts<123,124,125,126>
  mov r2.xyzw, x1[4].xyzw  // m<13:Inf,14:Inf,15:Inf,16:Inf>
  mov x0[39].xyz, r1.xyzx  // outVerts<130,131,132>
  mov x0[40].xyzw, r2.xyzw  // outVerts<133,134,135,136>
  mov x0[42].xyz, v[1][0].xyzx  // outVerts<140,141,142>
  mov x0[43].xyzw, v[1][1].xyzw  // outVerts<143,144,145,146>
  mov r0.y, l(0)  // i<0: 0>
  mov r0.z, r0.y  // i<0>
  loop 
    ilt r0.w, r0.z, l(15)
    breakc_z r0.w
    imul null, r0.w, r0.z, l(3)
    mov x0[r0.w + 1].xyzw, v[0][1].xyzw  // outVerts[r0.w/3]<3:Inf,4:Inf,5:Inf,6:Inf>
    iadd r0.z, r0.z, l(1)  // i<0>
  endloop 

#line 213
  mov r1.xyz, x0[0].xyzx  // outVerts<0:Inf,1:Inf,2:Inf>
  mov r2.xyzw, x0[1].xyzw  // outVerts<3:Inf,4:Inf,5:Inf,6:Inf>
  mov r3.xyz, x0[3].xyzx  // outVerts<10:Inf,11:Inf,12:Inf>
  mov r4.xyzw, x0[4].xyzw  // outVerts<13:Inf,14:Inf,15:Inf,16:Inf>
  mov r5.xyz, x0[6].xyzx  // outVerts<20:Inf,21:Inf,22:Inf>
  mov r6.xyzw, x0[7].xyzw  // outVerts<23:Inf,24:Inf,25:Inf,26:Inf>
  mov r7.xyz, x0[9].xyzx  // outVerts<30:NaN:Inf,31:NaN:Inf,32:NaN:Inf>
  mov r8.xyzw, x0[10].xyzw  // outVerts<33:Inf,34:Inf,35:Inf,36:Inf>
  mov r9.xyz, x0[12].xyzx  // outVerts<40:Inf,41:Inf,42:Inf>
  mov r10.xyzw, x0[13].xyzw  // outVerts<43:Inf,44:Inf,45:Inf,46:Inf>
  mov r11.xyz, x0[15].xyzx  // outVerts<50:NaN:Inf,51:NaN:Inf,52:NaN:Inf>
  mov r12.xyzw, x0[16].xyzw  // outVerts<53:Inf,54:Inf,55:Inf,56:Inf>
  mov r13.xyz, x0[18].xyzx  // outVerts<60:Inf,61:Inf,62:Inf>
  mov r14.xyzw, x0[19].xyzw  // outVerts<63:Inf,64:Inf,65:Inf,66:Inf>
  mov r15.xyz, x0[21].xyzx  // outVerts<70:Inf,71:Inf,72:Inf>
  mov r16.xyzw, x0[22].xyzw  // outVerts<73:Inf,74:Inf,75:Inf,76:Inf>
  mov r17.xyz, x0[24].xyzx  // outVerts<80:Inf,81:Inf,82:Inf>
  mov r18.xyzw, x0[25].xyzw  // outVerts<83:Inf,84:Inf,85:Inf,86:Inf>
  mov r19.xyz, x0[27].xyzx  // outVerts<90:Inf,91:Inf,92:Inf>
  mov r20.xyzw, x0[28].xyzw  // outVerts<93:Inf,94:Inf,95:Inf,96:Inf>
  mov r21.xyz, x0[30].xyzx  // outVerts<100:Inf,101:Inf,102:Inf>
  mov r22.xyzw, x0[31].xyzw  // outVerts<103:Inf,104:Inf,105:Inf,106:Inf>
  mov r23.xyz, x0[33].xyzx  // outVerts<110:NaN:Inf,111:NaN:Inf,112:NaN:Inf>
  mov r24.xyzw, x0[34].xyzw  // outVerts<113:Inf,114:Inf,115:Inf,116:Inf>
  mov r25.xyz, x0[36].xyzx  // outVerts<120:Inf,121:Inf,122:Inf>
  mov r26.xyzw, x0[37].xyzw  // outVerts<123:Inf,124:Inf,125:Inf,126:Inf>
  mov r27.xyz, x0[39].xyzx  // outVerts<130:Inf,131:Inf,132:Inf>
  mov r28.xyzw, x0[40].xyzw  // outVerts<133:Inf,134:Inf,135:Inf,136:Inf>
  mov r29.xyz, x0[42].xyzx  // outVerts<140:Inf,141:Inf,142:Inf>
  mov r30.xyzw, x0[43].xyzw  // outVerts<143:Inf,144:Inf,145:Inf,146:Inf>
  nop 

#line 165
  mov r1.w, l(0)
  dp4 r0.y, r1.xyzw, r1.xyzw
  rsq r0.y, r0.y
  mul r0.yzw, r0.yyyy, r1.xxyz
  mul r1.xyz, r0.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r0.yzw, r1.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r31.xyz, x3[3].xyzx  // gout<11:Inf,12:Inf,13:Inf>
  mov r1.w, l(1.000000)
  dp4 r31.w, r1.xyzw, cb1[16].xyzw
  dp4 r32.x, r1.xyzw, cb1[17].xyzw
  dp4 r32.y, r1.xyzw, cb1[18].xyzw
  dp4 r1.x, r1.xyzw, cb1[19].xyzw

#line 165
  mov r3.w, l(0)
  dp4 r1.y, r3.xyzw, r3.xyzw
  rsq r1.y, r1.y
  mul r1.yzw, r1.yyyy, r3.xxyz
  mul r3.xyz, r1.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r1.yzw, r3.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r33.xyz, x3[7].xyzx  // gout<25:Inf,26:Inf,27:Inf>
  mov r3.w, l(1.000000)
  dp4 r32.z, r3.xyzw, cb1[16].xyzw
  dp4 r32.w, r3.xyzw, cb1[17].xyzw
  dp4 r33.w, r3.xyzw, cb1[18].xyzw
  dp4 r3.x, r3.xyzw, cb1[19].xyzw

#line 165
  mov r5.w, l(0)
  dp4 r3.y, r5.xyzw, r5.xyzw
  rsq r3.y, r3.y
  mul r3.yzw, r3.yyyy, r5.xxyz
  mul r5.xyz, r3.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r3.yzw, r5.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r34.xyz, x3[11].xyzx  // gout<39:Inf,40:Inf,41:Inf>
  mov r5.w, l(1.000000)
  dp4 r34.w, r5.xyzw, cb1[16].xyzw
  dp4 r35.x, r5.xyzw, cb1[17].xyzw
  dp4 r35.y, r5.xyzw, cb1[18].xyzw
  dp4 r5.x, r5.xyzw, cb1[19].xyzw

#line 165
  mov r7.w, l(0)
  dp4 r5.y, r7.xyzw, r7.xyzw
  rsq r5.y, r5.y
  mul r5.yzw, r5.yyyy, r7.xxyz
  mul r7.xyz, r5.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r5.yzw, r7.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r36.xyz, x3[15].xyzx  // gout<53:Inf,54:Inf,55:Inf>
  mov r7.w, l(1.000000)
  dp4 r35.z, r7.xyzw, cb1[16].xyzw
  dp4 r35.w, r7.xyzw, cb1[17].xyzw
  dp4 r36.w, r7.xyzw, cb1[18].xyzw
  dp4 r7.x, r7.xyzw, cb1[19].xyzw

#line 165
  mov r9.w, l(0)
  dp4 r7.y, r9.xyzw, r9.xyzw
  rsq r7.y, r7.y
  mul r7.yzw, r7.yyyy, r9.xxyz
  mul r9.xyz, r7.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r7.yzw, r9.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r37.xyz, x3[19].xyzx  // gout<67:Inf,68:Inf,69:Inf>
  mov r9.w, l(1.000000)
  dp4 r37.w, r9.xyzw, cb1[16].xyzw
  dp4 r38.x, r9.xyzw, cb1[17].xyzw
  dp4 r38.y, r9.xyzw, cb1[18].xyzw
  dp4 r9.x, r9.xyzw, cb1[19].xyzw

#line 165
  mov r11.w, l(0)
  dp4 r9.y, r11.xyzw, r11.xyzw
  rsq r9.y, r9.y
  mul r9.yzw, r9.yyyy, r11.xxyz
  mul r11.xyz, r9.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r9.yzw, r11.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r39.xyz, x3[23].xyzx  // gout<81:Inf,82:Inf,83:Inf>
  mov r11.w, l(1.000000)
  dp4 r38.z, r11.xyzw, cb1[16].xyzw
  dp4 r38.w, r11.xyzw, cb1[17].xyzw
  dp4 r39.w, r11.xyzw, cb1[18].xyzw
  dp4 r11.x, r11.xyzw, cb1[19].xyzw

#line 165
  mov r13.w, l(0)
  dp4 r11.y, r13.xyzw, r13.xyzw
  rsq r11.y, r11.y
  mul r11.yzw, r11.yyyy, r13.xxyz
  mul r13.xyz, r11.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r11.yzw, r13.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r40.xyz, x3[27].xyzx  // gout<95:Inf,96:Inf,97:Inf>
  mov r13.w, l(1.000000)
  dp4 r40.w, r13.xyzw, cb1[16].xyzw
  dp4 r41.x, r13.xyzw, cb1[17].xyzw
  dp4 r41.y, r13.xyzw, cb1[18].xyzw
  dp4 r13.x, r13.xyzw, cb1[19].xyzw

#line 165
  mov r15.w, l(0)
  dp4 r13.y, r15.xyzw, r15.xyzw
  rsq r13.y, r13.y
  mul r13.yzw, r13.yyyy, r15.xxyz
  mul r15.xyz, r13.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r13.yzw, r15.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r42.xyz, x3[31].xyzx  // gout<109:Inf,110:Inf,111:Inf>
  mov r15.w, l(1.000000)
  dp4 r41.z, r15.xyzw, cb1[16].xyzw
  dp4 r41.w, r15.xyzw, cb1[17].xyzw
  dp4 r42.w, r15.xyzw, cb1[18].xyzw
  dp4 r15.x, r15.xyzw, cb1[19].xyzw

#line 165
  mov r17.w, l(0)
  dp4 r15.y, r17.xyzw, r17.xyzw
  rsq r15.y, r15.y
  mul r15.yzw, r15.yyyy, r17.xxyz
  mul r17.xyz, r15.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r15.yzw, r17.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r43.xyz, x3[35].xyzx  // gout<123:Inf,124:Inf,125:Inf>
  mov r17.w, l(1.000000)
  dp4 r43.w, r17.xyzw, cb1[16].xyzw
  dp4 r44.x, r17.xyzw, cb1[17].xyzw
  dp4 r44.y, r17.xyzw, cb1[18].xyzw
  dp4 r17.x, r17.xyzw, cb1[19].xyzw

#line 165
  mov r19.w, l(0)
  dp4 r17.y, r19.xyzw, r19.xyzw
  rsq r17.y, r17.y
  mul r17.yzw, r17.yyyy, r19.xxyz
  mul r19.xyz, r17.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r17.yzw, r19.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r45.xyz, x3[39].xyzx  // gout<137:Inf,138:Inf,139:Inf>
  mov r19.w, l(1.000000)
  dp4 r44.z, r19.xyzw, cb1[16].xyzw
  dp4 r44.w, r19.xyzw, cb1[17].xyzw
  dp4 r45.w, r19.xyzw, cb1[18].xyzw
  dp4 r19.x, r19.xyzw, cb1[19].xyzw

#line 165
  mov r21.w, l(0)
  dp4 r19.y, r21.xyzw, r21.xyzw
  rsq r19.y, r19.y
  mul r19.yzw, r19.yyyy, r21.xxyz
  mul r21.xyz, r19.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r19.yzw, r21.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r46.xyz, x3[43].xyzx  // gout<151:Inf,152:Inf,153:Inf>
  mov r21.w, l(1.000000)
  dp4 r46.w, r21.xyzw, cb1[16].xyzw
  dp4 r47.x, r21.xyzw, cb1[17].xyzw
  dp4 r47.y, r21.xyzw, cb1[18].xyzw
  dp4 r21.x, r21.xyzw, cb1[19].xyzw

#line 165
  mov r23.w, l(0)
  dp4 r21.y, r23.xyzw, r23.xyzw
  rsq r21.y, r21.y
  mul r21.yzw, r21.yyyy, r23.xxyz
  mul r23.xyz, r21.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r21.yzw, r23.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r48.xyz, x3[47].xyzx  // gout<165:Inf,166:Inf,167:Inf>
  mov r23.w, l(1.000000)
  dp4 r47.z, r23.xyzw, cb1[16].xyzw
  dp4 r47.w, r23.xyzw, cb1[17].xyzw
  dp4 r48.w, r23.xyzw, cb1[18].xyzw
  dp4 r23.x, r23.xyzw, cb1[19].xyzw

#line 165
  mov r25.w, l(0)
  dp4 r23.y, r25.xyzw, r25.xyzw
  rsq r23.y, r23.y
  mul r23.yzw, r23.yyyy, r25.xxyz
  mul r25.xyz, r23.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r23.yzw, r25.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r49.xyz, x3[51].xyzx  // gout<179:Inf,180:Inf,181:Inf>
  mov r25.w, l(1.000000)
  dp4 r49.w, r25.xyzw, cb1[16].xyzw
  dp4 r50.x, r25.xyzw, cb1[17].xyzw
  dp4 r50.y, r25.xyzw, cb1[18].xyzw
  dp4 r25.x, r25.xyzw, cb1[19].xyzw

#line 165
  mov r27.w, l(0)
  dp4 r25.y, r27.xyzw, r27.xyzw
  rsq r25.y, r25.y
  mul r25.yzw, r25.yyyy, r27.xxyz
  mul r27.xyz, r25.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r25.yzw, r27.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r51.xyz, x3[55].xyzx  // gout<193:Inf,194:Inf,195:Inf>
  mov r27.w, l(1.000000)
  dp4 r50.z, r27.xyzw, cb1[16].xyzw
  dp4 r50.w, r27.xyzw, cb1[17].xyzw
  dp4 r51.w, r27.xyzw, cb1[18].xyzw
  dp4 r27.x, r27.xyzw, cb1[19].xyzw

#line 165
  mov r29.w, l(0)
  dp4 r27.y, r29.xyzw, r29.xyzw
  rsq r27.y, r27.y
  mul r27.yzw, r27.yyyy, r29.xxyz
  mul r29.xyz, r27.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
  mov r27.yzw, r29.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 170
  mov r52.xyz, x3[59].xyzx  // gout<207:Inf,208:Inf,209:Inf>
  mov r29.w, l(1.000000)
  dp4 r52.w, r29.xyzw, cb1[16].xyzw
  dp4 r53.x, r29.xyzw, cb1[17].xyzw
  dp4 r53.y, r29.xyzw, cb1[18].xyzw
  dp4 r29.x, r29.xyzw, cb1[19].xyzw

#line 177
  mov o0.x, r31.w  // triStream<0>
  mov o0.y, r32.x  // triStream<0>
  mov o0.z, r32.y  // triStream<0>
  mov o0.w, r1.x  // triStream<0>
  mov o1.xyz, r0.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r2.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r31.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r32.z  // triStream<0>
  mov o0.y, r32.w  // triStream<0>
  mov o0.z, r33.w  // triStream<0>
  mov o0.w, r3.x  // triStream<0>
  mov o1.xyz, r1.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r4.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r33.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r34.w  // triStream<0>
  mov o0.y, r35.x  // triStream<0>
  mov o0.z, r35.y  // triStream<0>
  mov o0.w, r5.x  // triStream<0>
  mov o1.xyz, r3.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r6.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r34.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r35.z  // triStream<0>
  mov o0.y, r35.w  // triStream<0>
  mov o0.z, r36.w  // triStream<0>
  mov o0.w, r7.x  // triStream<0>
  mov o1.xyz, r5.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r8.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r36.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r37.w  // triStream<0>
  mov o0.y, r38.x  // triStream<0>
  mov o0.z, r38.y  // triStream<0>
  mov o0.w, r9.x  // triStream<0>
  mov o1.xyz, r7.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r10.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r37.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r38.z  // triStream<0>
  mov o0.y, r38.w  // triStream<0>
  mov o0.z, r39.w  // triStream<0>
  mov o0.w, r11.x  // triStream<0>
  mov o1.xyz, r9.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r12.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r39.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r40.w  // triStream<0>
  mov o0.y, r41.x  // triStream<0>
  mov o0.z, r41.y  // triStream<0>
  mov o0.w, r13.x  // triStream<0>
  mov o1.xyz, r11.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r14.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r40.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r41.z  // triStream<0>
  mov o0.y, r41.w  // triStream<0>
  mov o0.z, r42.w  // triStream<0>
  mov o0.w, r15.x  // triStream<0>
  mov o1.xyz, r13.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r16.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r42.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r43.w  // triStream<0>
  mov o0.y, r44.x  // triStream<0>
  mov o0.z, r44.y  // triStream<0>
  mov o0.w, r17.x  // triStream<0>
  mov o1.xyz, r15.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r18.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r43.xyzx  // triStream<0,0,0>
  emit_stream m0

#line 180
  cut_stream m0
  mov o0.x, r32.z  // triStream<0>
  mov o0.y, r32.w  // triStream<0>
  mov o0.z, r33.w  // triStream<0>
  mov o0.w, r3.x  // triStream<0>
  mov o1.xyz, r1.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r4.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r33.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r44.z  // triStream<0>
  mov o0.y, r44.w  // triStream<0>
  mov o0.z, r45.w  // triStream<0>
  mov o0.w, r19.x  // triStream<0>
  mov o1.xyz, r17.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r20.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r45.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r35.z  // triStream<0>
  mov o0.y, r35.w  // triStream<0>
  mov o0.z, r36.w  // triStream<0>
  mov o0.w, r7.x  // triStream<0>
  mov o1.xyz, r5.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r8.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r36.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r47.z  // triStream<0>
  mov o0.y, r47.w  // triStream<0>
  mov o0.z, r48.w  // triStream<0>
  mov o0.w, r23.x  // triStream<0>
  mov o1.xyz, r21.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r24.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r48.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r38.z  // triStream<0>
  mov o0.y, r38.w  // triStream<0>
  mov o0.z, r39.w  // triStream<0>
  mov o0.w, r11.x  // triStream<0>
  mov o1.xyz, r9.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r12.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r39.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r50.z  // triStream<0>
  mov o0.y, r50.w  // triStream<0>
  mov o0.z, r51.w  // triStream<0>
  mov o0.w, r27.x  // triStream<0>
  mov o1.xyz, r25.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r28.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r51.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r41.z  // triStream<0>
  mov o0.y, r41.w  // triStream<0>
  mov o0.z, r42.w  // triStream<0>
  mov o0.w, r15.x  // triStream<0>
  mov o1.xyz, r13.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r16.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r42.xyzx  // triStream<0,0,0>
  emit_stream m0
  cut_stream m0

#line 193
  mov o0.x, r44.z  // triStream<0>
  mov o0.y, r44.w  // triStream<0>
  mov o0.z, r45.w  // triStream<0>
  mov o0.w, r19.x  // triStream<0>
  mov o1.xyz, r17.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r20.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r45.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r46.w  // triStream<0>
  mov o0.y, r47.x  // triStream<0>
  mov o0.z, r47.y  // triStream<0>
  mov o0.w, r21.x  // triStream<0>
  mov o1.xyz, r19.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r22.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r46.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r47.z  // triStream<0>
  mov o0.y, r47.w  // triStream<0>
  mov o0.z, r48.w  // triStream<0>
  mov o0.w, r23.x  // triStream<0>
  mov o1.xyz, r21.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r24.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r48.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r49.w  // triStream<0>
  mov o0.y, r50.x  // triStream<0>
  mov o0.z, r50.y  // triStream<0>
  mov o0.w, r25.x  // triStream<0>
  mov o1.xyz, r23.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r26.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r49.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r50.z  // triStream<0>
  mov o0.y, r50.w  // triStream<0>
  mov o0.z, r51.w  // triStream<0>
  mov o0.w, r27.x  // triStream<0>
  mov o1.xyz, r25.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r28.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r51.xyzx  // triStream<0,0,0>
  emit_stream m0
  cut_stream m0
  mov o0.x, r46.w  // triStream<0>
  mov o0.y, r47.x  // triStream<0>
  mov o0.z, r47.y  // triStream<0>
  mov o0.w, r21.x  // triStream<0>
  mov o1.xyz, r19.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r22.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r46.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r52.w  // triStream<0>
  mov o0.y, r53.x  // triStream<0>
  mov o0.z, r53.y  // triStream<0>
  mov o0.w, r29.x  // triStream<0>
  mov o1.xyz, r27.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r30.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r52.xyzx  // triStream<0,0,0>
  emit_stream m0
  mov o0.x, r49.w  // triStream<0>
  mov o0.y, r50.x  // triStream<0>
  mov o0.z, r50.y  // triStream<0>
  mov o0.w, r25.x  // triStream<0>
  mov o1.xyz, r23.yzwy  // triStream<0,0,0>
  mov o2.xyzw, r26.xyzw  // triStream<0,0,0,0>
  mov o3.xyz, r49.xyzx  // triStream<0,0,0>
  emit_stream m0

#line 211
else 

#line 216
  lt r0.x, r0.x, l(30.000000)
  if_nz r0.x
    nop 

#line 66
    add r0.xyz, v[1][0].xyzx, v[0][0].xyzx
    mul r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    add r1.xyz, v[2][0].xyzx, v[1][0].xyzx
    mul r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    add r2.xyz, v[0][0].xyzx, v[2][0].xyzx
    mul r2.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
    mov r3.xyzw, x5[1].xyzw  // m<3:Inf,4:Inf,5:Inf,6:Inf>
    mov r4.xyzw, x5[4].xyzw  // m<13:Inf,14:Inf,15:Inf,16:Inf>
    mov r5.xyzw, x5[7].xyzw  // m<23:Inf,24:Inf,25:Inf,26:Inf>

#line 76
    mov x4[0].xyz, v[0][0].xyzx  // outVerts<0,1,2>
    mov x4[1].xyzw, v[0][1].xyzw  // outVerts<3,4,5,6>
    mov x4[2].xyz, v[0][2].xyzx  // outVerts<7,8,9>
    mov x4[3].xyz, r0.xyzx  // outVerts<10,11,12>
    mov x4[4].xyzw, r3.xyzw  // outVerts<13,14,15,16>
    mov x4[5].xyz, r0.xyzx  // outVerts<17,18,19>
    mov x4[6].xyz, r2.xyzx  // outVerts<20,21,22>
    mov x4[7].xyzw, r5.xyzw  // outVerts<23,24,25,26>
    mov x4[8].xyz, r2.xyzx  // outVerts<27,28,29>
    mov x4[9].xyz, r1.xyzx  // outVerts<30,31,32>
    mov x4[10].xyzw, r4.xyzw  // outVerts<33,34,35,36>
    mov x4[11].xyz, r1.xyzx  // outVerts<37,38,39>
    mov x4[12].xyz, v[2][0].xyzx  // outVerts<40,41,42>
    mov x4[13].xyzw, v[2][1].xyzw  // outVerts<43,44,45,46>
    mov x4[14].xyz, v[2][2].xyzx  // outVerts<47,48,49>
    mov x4[15].xyz, v[1][0].xyzx  // outVerts<50,51,52>
    mov x4[16].xyzw, v[1][1].xyzw  // outVerts<53,54,55,56>
    mov x4[17].xyz, v[1][2].xyzx  // outVerts<57,58,59>
    mov r0.x, l(0)  // i<0: 0>
    mov r0.y, r0.x  // i<0>
    loop 
      ilt r0.z, r0.y, l(6)
      breakc_z r0.z
      imul null, r0.z, r0.y, l(3)
      mov x4[r0.z + 1].xyzw, v[0][1].xyzw  // outVerts[r0.z/3]<3:Inf,4:Inf,5:Inf,6:Inf>
      iadd r0.y, r0.y, l(1)  // i<0>
    endloop 

#line 218
    mov r0.xyz, x4[0].xyzx  // outVerts<0:Inf,1:Inf,2:Inf>
    mov r1.xyzw, x4[1].xyzw  // outVerts<3:Inf,4:Inf,5:Inf,6:Inf>
    mov r2.xyz, x4[2].xyzx  // outVerts<7:Inf,8:Inf,9:Inf>
    mov r3.xyz, x4[3].xyzx  // outVerts<10:Inf,11:Inf,12:Inf>
    mov r4.xyzw, x4[4].xyzw  // outVerts<13:Inf,14:Inf,15:Inf,16:Inf>
    mov r5.xyz, x4[5].xyzx  // outVerts<17:Inf,18:Inf,19:Inf>
    mov r6.xyz, x4[6].xyzx  // outVerts<20:Inf,21:Inf,22:Inf>
    mov r7.xyzw, x4[7].xyzw  // outVerts<23:Inf,24:Inf,25:Inf,26:Inf>
    mov r8.xyz, x4[8].xyzx  // outVerts<27:Inf,28:Inf,29:Inf>
    mov r9.xyz, x4[9].xyzx  // outVerts<30:Inf,31:Inf,32:Inf>
    mov r10.xyzw, x4[10].xyzw  // outVerts<33:Inf,34:Inf,35:Inf,36:Inf>
    mov r11.xyz, x4[11].xyzx  // outVerts<37:Inf,38:Inf,39:Inf>
    mov r12.xyz, x4[12].xyzx  // outVerts<40:Inf,41:Inf,42:Inf>
    mov r13.xyzw, x4[13].xyzw  // outVerts<43:Inf,44:Inf,45:Inf,46:Inf>
    mov r14.xyz, x4[14].xyzx  // outVerts<47:Inf,48:Inf,49:Inf>
    mov r15.xyz, x4[15].xyzx  // outVerts<50:Inf,51:Inf,52:Inf>
    mov r16.xyzw, x4[16].xyzw  // outVerts<53:Inf,54:Inf,55:Inf,56:Inf>
    mov r17.xyz, x4[17].xyzx  // outVerts<57:Inf,58:Inf,59:Inf>
    nop 

#line 134
    mov r0.w, l(0)
    dp4 r0.w, r0.xyzw, r0.xyzw
    rsq r0.w, r0.w
    mul r0.xyz, r0.wwww, r0.xyzx
    mul r0.xyz, r0.xyzx, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r18.xyz, r0.xyzx  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r0.w, l(1.000000)
    dp4 r2.w, r0.xyzw, cb1[16].xyzw
    dp4 r5.w, r0.xyzw, cb1[17].xyzw
    dp4 r8.w, r0.xyzw, cb1[18].xyzw
    dp4 r0.x, r0.xyzw, cb1[19].xyzw

#line 134
    mov r3.w, l(0)
    dp4 r0.y, r3.xyzw, r3.xyzw
    rsq r0.y, r0.y
    mul r0.yzw, r0.yyyy, r3.xxyz
    mul r3.xyz, r0.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r0.yzw, r3.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r3.w, l(1.000000)
    dp4 r11.w, r3.xyzw, cb1[16].xyzw
    dp4 r14.w, r3.xyzw, cb1[17].xyzw
    dp4 r17.w, r3.xyzw, cb1[18].xyzw
    dp4 r3.x, r3.xyzw, cb1[19].xyzw

#line 134
    mov r6.w, l(0)
    dp4 r3.y, r6.xyzw, r6.xyzw
    rsq r3.y, r3.y
    mul r3.yzw, r3.yyyy, r6.xxyz
    mul r6.xyz, r3.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r3.yzw, r6.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r6.w, l(1.000000)
    dp4 r18.w, r6.xyzw, cb1[16].xyzw
    dp4 r19.x, r6.xyzw, cb1[17].xyzw
    dp4 r19.y, r6.xyzw, cb1[18].xyzw
    dp4 r6.x, r6.xyzw, cb1[19].xyzw

#line 134
    mov r9.w, l(0)
    dp4 r6.y, r9.xyzw, r9.xyzw
    rsq r6.y, r6.y
    mul r6.yzw, r6.yyyy, r9.xxyz
    mul r9.xyz, r6.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r6.yzw, r9.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r9.w, l(1.000000)
    dp4 r19.z, r9.xyzw, cb1[16].xyzw
    dp4 r19.w, r9.xyzw, cb1[17].xyzw
    dp4 r20.x, r9.xyzw, cb1[18].xyzw
    dp4 r9.x, r9.xyzw, cb1[19].xyzw

#line 134
    mov r12.w, l(0)
    dp4 r9.y, r12.xyzw, r12.xyzw
    rsq r9.y, r9.y
    mul r9.yzw, r9.yyyy, r12.xxyz
    mul r12.xyz, r9.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r9.yzw, r12.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r12.w, l(1.000000)
    dp4 r20.y, r12.xyzw, cb1[16].xyzw
    dp4 r20.z, r12.xyzw, cb1[17].xyzw
    dp4 r20.w, r12.xyzw, cb1[18].xyzw
    dp4 r12.x, r12.xyzw, cb1[19].xyzw

#line 134
    mov r15.w, l(0)
    dp4 r12.y, r15.xyzw, r15.xyzw
    rsq r12.y, r12.y
    mul r12.yzw, r12.yyyy, r15.xxyz
    mul r15.xyz, r12.yzwy, l(4.000000, 4.000000, 4.000000, 0.000000)  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>
    mov r12.yzw, r15.xxyz  // temp<0:NaN:Inf,1:NaN:Inf,2:NaN:Inf>

#line 141
    mov r15.w, l(1.000000)
    dp4 r21.x, r15.xyzw, cb1[16].xyzw
    dp4 r21.y, r15.xyzw, cb1[17].xyzw
    dp4 r21.z, r15.xyzw, cb1[18].xyzw
    dp4 r15.x, r15.xyzw, cb1[19].xyzw

#line 148
    mov o0.x, r2.w  // triStream<0>
    mov o0.y, r5.w  // triStream<0>
    mov o0.z, r8.w  // triStream<0>
    mov o0.w, r0.x  // triStream<0>
    mov o1.xyz, r18.xyzx  // triStream<0,0,0>
    mov o2.xyzw, r1.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r2.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r11.w  // triStream<0>
    mov o0.y, r14.w  // triStream<0>
    mov o0.z, r17.w  // triStream<0>
    mov o0.w, r3.x  // triStream<0>
    mov o1.xyz, r0.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r4.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r5.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r18.w  // triStream<0>
    mov o0.y, r19.x  // triStream<0>
    mov o0.z, r19.y  // triStream<0>
    mov o0.w, r6.x  // triStream<0>
    mov o1.xyz, r3.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r7.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r8.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r19.z  // triStream<0>
    mov o0.y, r19.w  // triStream<0>
    mov o0.z, r20.x  // triStream<0>
    mov o0.w, r9.x  // triStream<0>
    mov o1.xyz, r6.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r10.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r11.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r20.y  // triStream<0>
    mov o0.y, r20.z  // triStream<0>
    mov o0.z, r20.w  // triStream<0>
    mov o0.w, r12.x  // triStream<0>
    mov o1.xyz, r9.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r13.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r14.xyzx  // triStream<0,0,0>
    emit_stream m0

#line 151
    cut_stream m0
    mov o0.x, r11.w  // triStream<0>
    mov o0.y, r14.w  // triStream<0>
    mov o0.z, r17.w  // triStream<0>
    mov o0.w, r3.x  // triStream<0>
    mov o1.xyz, r0.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r4.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r5.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r21.x  // triStream<0>
    mov o0.y, r21.y  // triStream<0>
    mov o0.z, r21.z  // triStream<0>
    mov o0.w, r15.x  // triStream<0>
    mov o1.xyz, r12.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r16.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r17.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r19.z  // triStream<0>
    mov o0.y, r19.w  // triStream<0>
    mov o0.z, r20.x  // triStream<0>
    mov o0.w, r9.x  // triStream<0>
    mov o1.xyz, r6.yzwy  // triStream<0,0,0>
    mov o2.xyzw, r10.xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r11.xyzx  // triStream<0,0,0>
    emit_stream m0

#line 216
  else 

#line 229
    mov r0.xyz, x6[3].xyzx  // gout<11:Inf,12:Inf,13:Inf>
    mov r1.xyz, v[0][0].xyzx
    mov r1.w, l(1.000000)
    dp4 r0.w, r1.xyzw, cb1[16].xyzw
    dp4 r2.x, r1.xyzw, cb1[17].xyzw
    dp4 r2.y, r1.xyzw, cb1[18].xyzw
    dp4 r1.x, r1.xyzw, cb1[19].xyzw
    mov r1.yzw, x6[7].xxyz  // gout<25:Inf,26:Inf,27:Inf>
    mov r3.xyz, v[1][0].xyzx
    mov r3.w, l(1.000000)
    dp4 r2.z, r3.xyzw, cb1[16].xyzw
    dp4 r2.w, r3.xyzw, cb1[17].xyzw
    dp4 r4.x, r3.xyzw, cb1[18].xyzw
    dp4 r3.x, r3.xyzw, cb1[19].xyzw
    mov r3.yzw, x6[11].xxyz  // gout<39:Inf,40:Inf,41:Inf>
    mov r5.xyz, v[2][0].xyzx
    mov r5.w, l(1.000000)
    dp4 r4.y, r5.xyzw, cb1[16].xyzw
    dp4 r4.z, r5.xyzw, cb1[17].xyzw
    dp4 r4.w, r5.xyzw, cb1[18].xyzw
    dp4 r5.x, r5.xyzw, cb1[19].xyzw

#line 233
    mov o0.x, r0.w  // triStream<0>
    mov o0.y, r2.x  // triStream<0>
    mov o0.z, r2.y  // triStream<0>
    mov o0.w, r1.x  // triStream<0>
    mov o1.xyz, v[0][0].xyzx  // triStream<0,0,0>
    mov o2.xyzw, v[0][1].xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r0.xyzx  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r2.z  // triStream<0>
    mov o0.y, r2.w  // triStream<0>
    mov o0.z, r4.x  // triStream<0>
    mov o0.w, r3.x  // triStream<0>
    mov o1.xyz, v[1][0].xyzx  // triStream<0,0,0>
    mov o2.xyzw, v[1][1].xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r1.yzwy  // triStream<0,0,0>
    emit_stream m0
    mov o0.x, r4.y  // triStream<0>
    mov o0.y, r4.z  // triStream<0>
    mov o0.z, r4.w  // triStream<0>
    mov o0.w, r5.x  // triStream<0>
    mov o1.xyz, v[2][0].xyzx  // triStream<0,0,0>
    mov o2.xyzw, v[2][1].xyzw  // triStream<0,0,0,0>
    mov o3.xyz, r3.yzwy  // triStream<0,0,0>
    emit_stream m0

#line 216
  endif 

#line 211
endif 

#line 208
ret 
// Approximately 725 instruction slots used
